### ISSUE TITLE
Shouldn't the route-target import/export be available per MUP route type?

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/srv6-mobile#5]

**Comment by matsusato3** [comment]
Under BGP-MUP SAFI, 4 route types are defined. Each type should be configured with different route-target import/export policy to avoid mis-import/export by other route type policy.

**Comment by mjethanandani** [comment]
If I understand you correctly, you are looking for something like this:

```
  protocol BGP b1
    global route-distinguisher 33.33.33.33:60001
    global afi-safi IPV4_MUP
      rt-afi-safi IPV4_MUP
        route-target 100:4000 export            
```
